
MK:=mkdir
RM:=rm -r

DEBUG ?= 0

ifneq ($(DEBUG),1)
NO_ECHO:=@
else
NO_ECHO:=
endif


ifneq ($(filter clean,$(MAKECMDGOALS)),) #  clean existed

OTHER_GOALS=$(filter-out clean,$(MAKECMDGOALS))

ifneq (,$(OTHER_GOALS))
$(info nopt find command)\
$(error stop)
else
.PHONY: clean
clean:
    $(RM) $(BUILD_DIR)
endif

else        # clean not existed




endif





