/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stdio.h"
#include "stm32f4xx.h"
#include "dma.h"
#include "adc_dma.h"

extern uint16_t adc_raw_data[NUM_OF_CHNANELS];

int main(void)
{
    /* Loop forever */
	printf("Hello DMA ADC \n");
	adc_dma_init();


	while(1)
	{

	}
}

