TARGET_NAME:=boot
BUILD_DIR:=_build
COMMON_DIR:=../Common
OBJS_DIR:=$(BUILD_DIR)/objs

PROJ_DIR:=./

CCFLAG +=

ASMFLAG +=

CXFLAG +=

SRC_FILES +=\



.PHONY: default help


default: $(TARGET_NAME)

include $(COMMON_DIR)/Makefile.common

help:
	echo help






