/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stdio.h"
#include "stm32f4xx.h"
#include "dma.h"
#include "adc_dma.h"

extern uint16_t adc_raw_data[NUM_OF_SAMPLES];
volatile uint8_t g_transfer_cmplt;

int main(void)
{
	g_transfer_cmplt = 0;
    /* Loop forever */
	printf("Hello DMA ADC \n");
//	adc_dma_init();
	adc_tim_dma_init();


	while(1)
	{
		if (g_transfer_cmplt)
		{
			g_transfer_cmplt = 0;
			for (int i = 0; i < NUM_OF_SAMPLES;i++)
			{
				printf("Sample[%d] = %d \n",i, adc_raw_data[i]);
			}
			for (int i = 0; i < 90000; i++){}
		}

	}
}

void DMA2_Stream0_IRQHandler()
{
	/* Check if transfer complete interrupt occured */
	if((DMA2->LISR) & LISR_TCIF0)
	{
		g_transfer_cmplt = 1;
		/* Clear flag*/
		DMA2->LIFCR |= LIFCR_CTCIF0;
	}
//	/* Check if transfer complete interrupt occured */
//	if((DMA2->LISR) & LISR_TEIF0)
//	{
////		g_transfer_cmplt = 0;
//			/* Clear flag*/
//		DMA2->LIFCR |= LIFCR_CTEIF0;
//	}
}

